"""Cache invalidation endpoints.

DELETE /v1/cache                          — clear the entire cache
DELETE /v1/cache/context/{context_key}    — invalidate by system-prompt hash
DELETE /v1/cache/model/{model}            — invalidate by model name
DELETE /v1/cache/prefix?q={prefix}        — invalidate by query prefix
DELETE /v1/cache/tag/{tag}                — invalidate by tag

All endpoints return {"deleted": <int>} so callers can confirm scope.
"""

from __future__ import annotations

from fastapi import APIRouter, Query

from .dependencies import VectorStoreDep

invalidation_router = APIRouter(tags=["cache-invalidation"])


@invalidation_router.delete("/v1/cache")
def clear_all(store: VectorStoreDep) -> dict:
    """Remove every entry from the cache."""
    before = store.size()
    store.clear()
    return {"deleted": before}


@invalidation_router.delete("/v1/cache/context/{context_key}")
def invalidate_by_context(context_key: str, store: VectorStoreDep) -> dict:
    """Invalidate all entries stored under *context_key*.

    The context key is the SHA-256 hex digest of the LLM context
    (system_prompt + model + temperature + max_tokens) produced by
    ``CacheKeyBuilder``.  Call this whenever a system prompt changes so
    stale responses are never served.
    """
    deleted = store.invalidate_by_context_key(context_key)
    return {"deleted": deleted, "context_key": context_key}


@invalidation_router.delete("/v1/cache/model/{model:path}")
def invalidate_by_model(model: str, store: VectorStoreDep) -> dict:
    """Invalidate all entries whose stored model name equals *model*.

    Use this after a model upgrade (e.g. ``gpt-4o`` → ``gpt-4o-2024-11-20``)
    to ensure clients no longer receive responses generated by the old model.
    """
    deleted = store.invalidate_by_model(model)
    return {"deleted": deleted, "model": model}


@invalidation_router.delete("/v1/cache/prefix")
def invalidate_by_prefix(
    store: VectorStoreDep,
    q: str = Query(..., description="Query prefix to match (case-insensitive)."),
) -> dict:
    """Invalidate all entries whose original query starts with *q*.

    Useful for topic-scoped manual invalidation — e.g. wiping all cached
    responses for queries beginning with ``"Tell me about our pricing"``.
    """
    deleted = store.invalidate_by_query_prefix(q)
    return {"deleted": deleted, "prefix": q}


@invalidation_router.delete("/v1/cache/tag/{tag}")
def invalidate_by_tag(tag: str, store: VectorStoreDep) -> dict:
    """Invalidate all entries that carry *tag* in their ``cache_tags``.

    Tags are set at request time by including ``"cache_tags": ["my-tag"]``
    in the ``POST /v1/chat/completions`` body (non-OpenAI extension field).
    """
    deleted = store.invalidate_by_tag(tag)
    return {"deleted": deleted, "tag": tag}
